import type { Entity, User } from "../types";
export const demoUsers: User[] = [
  {
    id: "u0",
    name: "Neeraj Kumar",
    email: "director@creativeadhyayan.com",
    role: "director",
    team_id: "Creative",
    active: true,
  },
  {
    id: "u1",
    name: "Riya Sharma",
    email: "manager@creativeadhyayan.com",
    role: "manager",
    team_id: "Client Servicing",
    active: true,
  },
  ...[
    "Aman Verma",
    "Neha Singh",
    "Rahul Mehta",
    "Priya Kapoor",
    "Akash Jain",
    "Sneha Gupta",
    "Karan Shah",
    "Pooja Mishra",
    "Arjun Patel",
    "Anjali Rao",
    "Rohit Saini",
    "Nisha Yadav",
    "Vivek Joshi",
    "Meera Nair",
    "Dev Malhotra",
    "Isha Bansal",
    "Yash Sharma",
    "Kavya Gupta",
    "Aditya Kumar",
    "Simran Kaur",
  ].map((name, i) => ({
    id: "u" + (i + 2),
    name,
    email: name.toLowerCase().split(" ")[0] + "@demo.local",
    role: (i < 4 ? "team_lead" : "employee") as User["role"],
    reports_to: i < 4 ? "u1" : "u" + (2 + (i % 4)),
    team_id: [
      "Creative",
      "Performance Marketing",
      "Development",
      "Content",
      "Client Servicing",
    ][i % 5],
    active: true,
  })),
];
const clients = [
  "ABC Fashion",
  "Vrundavan City",
  "Shri Shyam Movers",
  "Fibo Market",
  "EducationVista",
  "Bloom Wellness",
  "Crestline Cricket",
  "Urban Roots",
];
export function seed(): Record<string, Entity[]> {
  const projects = [
    "September Social Campaign",
    "Phase 3 Launch",
    "Relocation Lead Campaign",
    "Trading Education Launch",
    "Expo Promotion",
    "Wellness Brand Refresh",
    "Cricket Academy Website",
    "Festive E-commerce Campaign",
    "creative-crew Admissions",
    "SEO Growth Sprint",
  ];
  const taskNames = [
    "Create campaign strategy",
    "Design Instagram carousel",
    "Edit launch reel",
    "Write campaign captions",
    "Build conversion landing page",
    "Review ad creatives",
    "Schedule social posts",
    "Prepare monthly report",
    "Optimize Google Ads",
    "Publish SEO article",
  ];
  return {
    employees: demoUsers.map((u, i) => ({
      ...u,
      status: "Active",
      department: u.team_id,
      description: [
        "Graphic Design, Video Editing",
        "Meta Ads, Google Ads",
        "React, WordPress",
        "Copywriting, SEO",
        "Client Communication",
      ][i % 5],
    })),
    clients: clients.map((name, i) => ({
      id: "c" + i,
      name,
      status: "Active",
      email: "hello@" + name.toLowerCase().replaceAll(" ", "") + ".example",
      amount: 45000 + i * 5000,
      assignee: "u1",
      description: "Monthly marketing partnership",
    })),
    projects: projects.map((name, i) => ({
      id: "p" + i,
      name,
      status: i === 3 ? "At Risk" : i === 8 ? "Planning" : "Active",
      client_id: "c" + (i % 8),
      team_id: [
        "Creative",
        "Performance Marketing",
        "Development",
        "Content",
        "Client Servicing",
      ][i % 5],
      department: [
        "Creative",
        "Performance Marketing",
        "Development",
        "Content",
        "Client Servicing",
      ][i % 5],
      assignee: "u" + ((i % 4) + 2),
      due: "2026-09-" + (18 + i),
      description:
        "Strategy, creative production and delivery. Keep client feedback connected to each deliverable.",
      hours: 40 + i * 8,
    })),
    tasks: Array.from({ length: 60 }, (_, i) => ({
      id: "t" + i,
      name: taskNames[i % 10] + " · " + clients[i % 8],
      status: [
        "To Do",
        "In Progress",
        "Internal Review",
        "Completed",
        "Completed",
        "Revision",
      ][i % 6],
      project_id: "p" + (i % 10),
      client_id: "c" + (i % 8),
      assignee: "u" + ((i % 20) + 2),
      team_id: [
        "Creative",
        "Performance Marketing",
        "Development",
        "Content",
        "Client Servicing",
      ][i % 5],
      department: [
        "Creative",
        "Performance Marketing",
        "Development",
        "Content",
        "Client Servicing",
      ][i % 5],
      priority: ["High", "Medium", "Low"][i % 3],
      due: "2026-09-" + String(8 + (i % 20)).padStart(2, "0"),
      hours: 2 + (i % 6),
      description:
        "Follow the approved brand direction. Prepare the first draft, check dimensions and copy, then submit for internal review.",
      created_at: "2026-09-01T10:00:00Z",
    })),
    approvals: [],
    attendance: [],
    time_entries: [],
    comments: [],
    activity_logs: [],
    notifications: [
      {
        id: "n0",
        name: "Welcome to your creative-crew workspace",
        status: "Unread",
        description:
          "Explore the sample campaign, assign work and review your team capacity.",
      },
    ],
    requests: [],
    content_items: [
      {
        id: "co0",
        name: "September launch reel",
        status: "Scheduled",
        due: "2026-09-18",
        client_id: "c0",
        assignee: "u6",
        description: "Instagram · Reel",
      },
    ],
    documents: [
      {
        id: "d0",
        name: "Creative quality checklist",
        status: "Published",
        description:
          "1. Confirm brief and brand guidelines.\n2. Review copy and dimensions.\n3. Export a client-ready preview.\n4. Submit for internal review.",
      },
      {
        id: "d1",
        name: "One Platform. Every Skill You Need.",
        status: "Published",
        description:
          "creative-crew offers practical, industry-focused training in Graphic Design, Web Development, Digital Marketing, AI Tools and Video Editing. Online and offline learning are available.",
      },
    ],
    files: [],
    payroll: [],
    expenses: [
      {
        id: "e0",
        name: "Creative software subscriptions",
        status: "Paid",
        amount: 18500,
        due: "2026-09-01",
      },
    ],
    invoices: clients.map((name, i) => ({
      id: "i" + i,
      name: name + " · September retainer",
      client_id: "c" + i,
      status: i < 5 ? "Paid" : "Pending",
      amount: 45000 + i * 5000,
      due: "2026-09-30",
    })),
    automations: [
      {
        id: "a0",
        name: "Task completed → notify reviewer",
        status: "Active",
        description: "Notify the project manager when a task is completed.",
      },
    ],
    settings: [],
  };
}
