-- Run once in a new Supabase project. Demo data is intentionally separate.
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null,email text not null,role text not null check(role in ('super_admin','admin','leader','employee')), team_id text not null default 'Creative', active boolean not null default true,created_at timestamptz not null default now());
alter table public.profiles enable row level security;
create function public.current_role() returns text language sql stable security definer set search_path=public as $$select role from profiles where id=auth.uid() and active$$;
create function public.current_team() returns text language sql stable security definer set search_path=public as $$select team_id from profiles where id=auth.uid() and active$$;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select coalesce(current_role() in ('admin','super_admin'),false)$$;
create policy profiles_read on profiles for select to authenticated using (id=auth.uid() or is_admin() or (current_role()='leader' and team_id=current_team()));
-- Profile writes are only performed by the authorized server function or employee sync trigger.
create table public.employees (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.employees enable row level security;
create index on public.employees(assignee);
create index on public.employees(team_id);
create table public.clients (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.clients enable row level security;
create index on public.clients(assignee);
create index on public.clients(team_id);
create table public.projects (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null);
alter table public.projects enable row level security;
create index on public.projects(assignee);
create index on public.projects(team_id);
create table public.tasks (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.tasks enable row level security;
create index on public.tasks(assignee);
create index on public.tasks(team_id);
create table public.attendance (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.attendance enable row level security;
create index on public.attendance(assignee);
create index on public.attendance(team_id);
create table public.time_entries (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.time_entries enable row level security;
create index on public.time_entries(assignee);
create index on public.time_entries(team_id);
create table public.comments (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null, task_id uuid references public.tasks(id) on delete cascade);
alter table public.comments enable row level security;
create index on public.comments(assignee);
create index on public.comments(team_id);
create table public.activity_logs (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.activity_logs enable row level security;
create index on public.activity_logs(assignee);
create index on public.activity_logs(team_id);
create table public.notifications (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.notifications enable row level security;
create index on public.notifications(assignee);
create index on public.notifications(team_id);
create table public.requests (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.requests enable row level security;
create index on public.requests(assignee);
create index on public.requests(team_id);
create table public.content_items (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.content_items enable row level security;
create index on public.content_items(assignee);
create index on public.content_items(team_id);
create table public.documents (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.documents enable row level security;
create index on public.documents(assignee);
create index on public.documents(team_id);
create table public.files (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.files enable row level security;
create index on public.files(assignee);
create index on public.files(team_id);
create table public.payroll (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.payroll enable row level security;
create index on public.payroll(assignee);
create index on public.payroll(team_id);
create table public.expenses (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.expenses enable row level security;
create index on public.expenses(assignee);
create index on public.expenses(team_id);
create table public.invoices (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.invoices enable row level security;
create index on public.invoices(assignee);
create index on public.invoices(team_id);
create table public.automations (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.automations enable row level security;
create index on public.automations(assignee);
create index on public.automations(team_id);
create table public.settings (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null);
alter table public.settings enable row level security;
create index on public.settings(assignee);
create index on public.settings(team_id);
create table public.approvals (id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'Active', description text, department text, email text, role text, assignee uuid references public.profiles(id), owner_id uuid references public.profiles(id) default auth.uid(),team_id text, due date, priority text, hours numeric not null default 0 check(hours>=0), amount numeric not null default 0 check(amount>=0), author text, storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_id uuid references public.clients(id) on delete set null, project_id uuid references public.projects(id) on delete set null, task_id uuid references public.tasks(id) on delete cascade);
alter table public.approvals enable row level security;
create index on public.approvals(assignee);
create index on public.approvals(team_id);
create function public.can_read_work(project uuid,assigned uuid,owner uuid,team text) returns boolean language sql stable security definer set search_path=public as $$select coalesce(is_admin() or (current_role() is not null and (assigned=auth.uid() or owner=auth.uid() or (current_role()='leader' and team=current_team()))),false)$$;
create policy employees_admin on public.employees for all to authenticated using(is_admin()) with check(is_admin());
create policy employees_read on public.employees for select to authenticated using(current_role() is not null and (id=auth.uid() or (current_role()='leader' and team_id=current_team())));
create policy clients_admin on public.clients for all to authenticated using(is_admin()) with check(is_admin());
create policy projects_admin on public.projects for all to authenticated using(is_admin()) with check(is_admin());
create policy projects_read on public.projects for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy projects_leader_insert on public.projects for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy projects_leader_update on public.projects for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy tasks_admin on public.tasks for all to authenticated using(is_admin()) with check(is_admin());
create policy tasks_read on public.tasks for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy tasks_leader_insert on public.tasks for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy tasks_leader_update on public.tasks for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy tasks_employee_update on public.tasks for update to authenticated using(current_role()='employee' and assignee=auth.uid()) with check(assignee=auth.uid());
create policy attendance_admin on public.attendance for all to authenticated using(is_admin()) with check(is_admin());
create policy attendance_read on public.attendance for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy attendance_own_insert on public.attendance for insert to authenticated with check(current_role() is not null and owner_id=auth.uid() and (assignee=auth.uid() or assignee is null) and team_id=current_team());
create policy attendance_own_update on public.attendance for update to authenticated using(current_role() is not null and owner_id=auth.uid()) with check(owner_id=auth.uid() and (assignee=auth.uid() or assignee is null));
create policy time_entries_admin on public.time_entries for all to authenticated using(is_admin()) with check(is_admin());
create policy time_entries_read on public.time_entries for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy time_entries_own_insert on public.time_entries for insert to authenticated with check(current_role() is not null and owner_id=auth.uid() and (assignee=auth.uid() or assignee is null) and team_id=current_team());
create policy time_entries_own_update on public.time_entries for update to authenticated using(current_role() is not null and owner_id=auth.uid()) with check(owner_id=auth.uid() and (assignee=auth.uid() or assignee is null));
create policy comments_admin on public.comments for all to authenticated using(is_admin()) with check(is_admin());
create policy comments_read on public.comments for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy comments_own_insert on public.comments for insert to authenticated with check(current_role() is not null and owner_id=auth.uid() and (assignee=auth.uid() or assignee is null) and team_id=current_team());
create policy comments_own_update on public.comments for update to authenticated using(current_role() is not null and owner_id=auth.uid()) with check(owner_id=auth.uid() and (assignee=auth.uid() or assignee is null));
create policy activity_logs_admin on public.activity_logs for select to authenticated using(is_admin());
create policy notifications_admin on public.notifications for all to authenticated using(is_admin()) with check(is_admin());
create policy notifications_read on public.notifications for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy notification_own_update on public.notifications for update to authenticated using(assignee=auth.uid() and current_role() is not null) with check(assignee=auth.uid());
create policy requests_admin on public.requests for all to authenticated using(is_admin()) with check(is_admin());
create policy requests_read on public.requests for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy requests_leader_insert on public.requests for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy requests_leader_update on public.requests for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy requests_own_insert on public.requests for insert to authenticated with check(current_role() is not null and owner_id=auth.uid() and (assignee=auth.uid() or assignee is null) and team_id=current_team());
create policy requests_own_update on public.requests for update to authenticated using(current_role() is not null and owner_id=auth.uid()) with check(owner_id=auth.uid() and (assignee=auth.uid() or assignee is null));
create policy content_items_admin on public.content_items for all to authenticated using(is_admin()) with check(is_admin());
create policy content_items_read on public.content_items for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy content_items_leader_insert on public.content_items for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy content_items_leader_update on public.content_items for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy documents_admin on public.documents for all to authenticated using(is_admin()) with check(is_admin());
create policy documents_read on public.documents for select to authenticated using(current_role() is not null);
create policy documents_leader_insert on public.documents for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy documents_leader_update on public.documents for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy files_admin on public.files for all to authenticated using(is_admin()) with check(is_admin());
create policy files_read on public.files for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
create policy files_leader_insert on public.files for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy files_leader_update on public.files for update to authenticated using(current_role()='leader' and team_id=current_team()) with check(current_role()='leader' and team_id=current_team() and (assignee is null or exists(select 1 from profiles p where p.id=assignee and p.team_id=current_team())));
create policy files_own_insert on public.files for insert to authenticated with check(current_role() is not null and owner_id=auth.uid() and (assignee=auth.uid() or assignee is null) and team_id=current_team());
create policy files_own_update on public.files for update to authenticated using(current_role() is not null and owner_id=auth.uid()) with check(owner_id=auth.uid() and (assignee=auth.uid() or assignee is null));
create policy payroll_admin on public.payroll for all to authenticated using(is_admin()) with check(is_admin());
create policy expenses_admin on public.expenses for all to authenticated using(is_admin()) with check(is_admin());
create policy invoices_admin on public.invoices for all to authenticated using(is_admin()) with check(is_admin());
create policy automations_admin on public.automations for all to authenticated using(is_admin()) with check(is_admin());
create policy settings_admin on public.settings for all to authenticated using(is_admin()) with check(is_admin());
create policy approvals_admin on public.approvals for all to authenticated using(is_admin()) with check(is_admin());
create policy approvals_read on public.approvals for select to authenticated using(can_read_work(null,assignee,owner_id,team_id));
-- Employee status updates immediately revoke data access for inactive profiles.
create function public.sync_employee_profile() returns trigger language plpgsql security definer set search_path=public as $$begin
if not is_admin() and current_user <> 'postgres' and auth.role() <> 'service_role' then raise exception 'Admin access required'; end if;
if current_role()='admin' and (new.role in ('admin','super_admin') or old.role in ('admin','super_admin')) then raise exception 'Only owner may manage administrators'; end if;
update profiles set name=new.name,email=new.email,role=coalesce(new.role,'employee'),team_id=coalesce(new.department,'Creative'),active=new.status not in ('Inactive','Exited') where id=new.id;
return new;end$$;
create trigger sync_employee after update on employees for each row execute function sync_employee_profile();
-- Prevent employees changing task responsibility, dates or priority through direct API calls.
create function public.guard_task_update() returns trigger language plpgsql set search_path=public as $$begin
if current_role()='employee' and (new.name is distinct from old.name or new.assignee is distinct from old.assignee or new.owner_id is distinct from old.owner_id or new.team_id is distinct from old.team_id or new.project_id is distinct from old.project_id or new.client_id is distinct from old.client_id or new.due is distinct from old.due or new.priority is distinct from old.priority or new.hours is distinct from old.hours or new.amount is distinct from old.amount) then raise exception 'Employees can only update task status and description';end if;return new;end$$;
create trigger guard_task before update on tasks for each row execute function guard_task_update();
-- Database audit runs even when changes are made outside the UI.
create function public.audit_record() returns trigger language plpgsql security definer set search_path=public as $$begin
insert into activity_logs(name,status,owner_id,description) values(coalesce(auth.uid()::text,'server')||' '||TG_OP||' '||TG_TABLE_NAME,'Recorded',auth.uid(),jsonb_build_object('old',case when TG_OP='INSERT' then null else to_jsonb(old) end,'new',case when TG_OP='DELETE' then null else to_jsonb(new) end)::text);return coalesce(new,old);end$$;
create trigger audit_tasks after insert or update or delete on tasks for each row execute function audit_record();
create trigger audit_projects after insert or update or delete on projects for each row execute function audit_record();
create trigger audit_employees after insert or update or delete on employees for each row execute function audit_record();
create trigger audit_payroll after insert or update or delete on payroll for each row execute function audit_record();
create trigger audit_clients after insert or update or delete on clients for each row execute function audit_record();
create trigger audit_expenses after insert or update or delete on expenses for each row execute function audit_record();
create trigger audit_invoices after insert or update or delete on invoices for each row execute function audit_record();
create function public.task_notification() returns trigger language plpgsql security definer set search_path=public as $$begin
if TG_OP='INSERT' or new.status is distinct from old.status or new.assignee is distinct from old.assignee then
insert into notifications(name,status,assignee,team_id,description) values(new.name||' · '||new.status,'Unread',new.assignee,new.team_id,'Task updated in your workspace.');
end if; return new; end$$;
create trigger task_notifications after insert or update on tasks for each row execute function task_notification();
insert into storage.buckets(id,name,public) values('agency-files','agency-files',false);
create policy agency_storage_select on storage.objects for select to authenticated using(bucket_id='agency-files' and (is_admin() or (current_role() is not null and (storage.foldername(name))[1]=auth.uid()::text)));
create policy agency_storage_insert on storage.objects for insert to authenticated with check(bucket_id='agency-files' and current_role() is not null and (storage.foldername(name))[1]=auth.uid()::text);
create policy agency_storage_delete on storage.objects for delete to authenticated using(bucket_id='agency-files' and (is_admin() or (current_role() is not null and (storage.foldername(name))[1]=auth.uid()::text)));
-- Enable realtime for operational changes. Other tables refresh after a mutation.
alter publication supabase_realtime add table public.tasks,public.notifications,public.projects,public.attendance;

alter table public.employees add column project_id uuid references public.projects(id) on delete set null, add column client_id uuid references public.clients(id) on delete set null;
alter table public.clients add column project_id uuid references public.projects(id) on delete set null,add column client_id uuid references public.clients(id) on delete set null;
alter table public.projects add column project_id uuid references public.projects(id) on delete set null;
create policy files_own_delete on files for delete to authenticated using(current_role() is not null and owner_id=auth.uid());

create policy project_employee_membership on projects for select to authenticated using(current_role()='employee' and exists(select 1 from tasks t where t.project_id=projects.id and t.assignee=auth.uid()));
create policy approvals_leader_insert on approvals for insert to authenticated with check(current_role()='leader' and team_id=current_team() and owner_id=auth.uid());

create function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger touch_employees before update on public.employees for each row execute function touch_updated_at();
create trigger touch_clients before update on public.clients for each row execute function touch_updated_at();
create trigger touch_projects before update on public.projects for each row execute function touch_updated_at();
create trigger touch_tasks before update on public.tasks for each row execute function touch_updated_at();
create trigger touch_attendance before update on public.attendance for each row execute function touch_updated_at();
create trigger touch_time_entries before update on public.time_entries for each row execute function touch_updated_at();
create trigger touch_comments before update on public.comments for each row execute function touch_updated_at();
create trigger touch_notifications before update on public.notifications for each row execute function touch_updated_at();
create trigger touch_requests before update on public.requests for each row execute function touch_updated_at();
create trigger touch_content_items before update on public.content_items for each row execute function touch_updated_at();
create trigger touch_documents before update on public.documents for each row execute function touch_updated_at();
create trigger touch_files before update on public.files for each row execute function touch_updated_at();
create trigger touch_payroll before update on public.payroll for each row execute function touch_updated_at();
create trigger touch_expenses before update on public.expenses for each row execute function touch_updated_at();
create trigger touch_invoices before update on public.invoices for each row execute function touch_updated_at();
create trigger touch_automations before update on public.automations for each row execute function touch_updated_at();
create trigger touch_settings before update on public.settings for each row execute function touch_updated_at();
create trigger touch_approvals before update on public.approvals for each row execute function touch_updated_at();
