import { useState } from "react";
import { Eye, MoreHorizontal, Pencil, Plus, Power, Search, ShieldCheck, Trash2, UserRoundCheck, Users } from "lucide-react";
import { z } from "zod";
import { useWorkspace } from "../services/workspace";
import { Avatar, Badge, Button, Modal } from "../components/ui";
import { canManage, manageableRole } from "../lib/permissions";
import { departments, roleLabels, type Entity, type Role } from "../types";

const schema = z.object({ name: z.string().trim().min(2, "Enter at least 2 characters."), email: z.string().trim().email("Enter a valid email."), phone: z.string().trim().regex(/^$|^[+\d][\d\s-]{8,14}$/, "Enter a valid phone number."), department: z.string().min(1), status: z.enum(["Active", "Inactive", "On Leave"]) });
type FormData = z.infer<typeof schema>;

export default function People() {
  const { user, data, save, remove } = useWorkspace();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("All"); const [department, setDepartment] = useState("All");
  const [edit, setEdit] = useState<Entity | null | undefined>(); const [view, setView] = useState<Entity | null>(null); const [removeRow, setRemoveRow] = useState<Entity | null>(null);
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (!user) return null;
  const currentUser = user;
  const targetRole = manageableRole(user.role);
  if (!targetRole) return <div className="empty"><ShieldCheck size={38}/><h1>Your profile</h1><p>Employees can view their work and profile, but cannot manage other accounts.</p></div>;
  const managedRole: Role = targetRole;
  const rows = (data.employees || []).filter(p => p.role === managedRole && canManage(currentUser, p as never)).filter(p => `${p.name} ${p.email} ${p.department}`.toLowerCase().includes(query.toLowerCase()) && (status === "All" || p.status === status) && (department === "All" || p.department === department));

  async function persist(values: FormData) {
    const parsed = schema.safeParse(values); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message);
    await save("employees", { ...edit, ...parsed.data, id: edit?.id, role: managedRole, team_id: parsed.data.department, reports_to: currentUser.id, active: parsed.data.status === "Active", joined_at: edit?.joined_at || new Date().toISOString().slice(0,10), description: `${roleLabels[managedRole]} · Reports to ${currentUser.name}` });
  }
  async function toggle(row: Entity) { try { setBusy(true); await save("employees", { ...row, status: row.status === "Active" ? "Inactive" : "Active", active: row.status !== "Active" }); setNotice(`${row.name} is now ${row.status === "Active" ? "inactive" : "active"}.`); } catch(e){setError((e as Error).message)} finally{setBusy(false)} }
  return <div className="people-page">
    <div className="page-heading"><div><span className="eyebrow"><UserRoundCheck size={14}/> ROLE-BASED PEOPLE MANAGEMENT</span><h1>Manage {roleLabels[managedRole]}s</h1><p className="muted">Create and manage only the role directly below your own access level.</p></div><Button onClick={() => setEdit(null)}><Plus size={17}/> Add {roleLabels[managedRole]}</Button></div>
    {(notice || error) && <div className={`people-notice ${error ? "danger" : "success"}`} role="status">{error || notice}<button onClick={() => {setNotice("");setError("")}}>×</button></div>}
    <div className="card people-summary"><span><Users size={22}/></span><div><strong>{rows.length}</strong><small>Visible {roleLabels[managedRole].toLowerCase()} accounts</small></div><i/><div><strong>{rows.filter(x => x.status === "Active").length}</strong><small>Currently active</small></div></div>
    <div className="toolbar card"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, email or department…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Inactive</option><option>On Leave</option></select><select value={department} onChange={e=>setDepartment(e.target.value)}><option>All</option>{departments.map(x=><option key={x}>{x}</option>)}</select></div>
    {!rows.length ? <div className="empty"><Users size={36}/><h3>No {roleLabels[managedRole].toLowerCase()} found</h3><p>Change your filters or add the first account.</p></div> : <div className="people-grid">{rows.map(row=><article className="card people-card" key={row.id}><div className="people-card-top"><Avatar name={row.name}/><Badge value={row.status}/><MoreHorizontal size={18}/></div><h3>{row.name}</h3><p>{row.email}</p><div className="people-meta"><span>{roleLabels[row.role!]}</span><span>{row.department}</span></div><div className="people-actions"><button onClick={()=>setView(row)}><Eye size={16}/> View</button><button onClick={()=>setEdit(row)}><Pencil size={16}/> Edit</button><button disabled={busy} onClick={()=>toggle(row)}><Power size={16}/> {row.status === "Active" ? "Disable" : "Enable"}</button><button className="danger" onClick={()=>setRemoveRow(row)}><Trash2 size={16}/></button></div></article>)}</div>}
    {edit !== undefined && <PeopleForm role={managedRole} row={edit || undefined} onClose={()=>setEdit(undefined)} onSave={async v=>{try{setBusy(true);setError("");await persist(v);setEdit(undefined);setNotice(`${roleLabels[managedRole]} ${edit ? "updated" : "created"} successfully.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}} busy={busy}/>} 
    {view && <Modal title={view.name} onClose={()=>setView(null)}><div className="person-detail"><Avatar name={view.name}/><Badge value={view.status}/><dl><div><dt>Role</dt><dd>{roleLabels[view.role!]}</dd></div><div><dt>Email</dt><dd>{view.email}</dd></div><div><dt>Department</dt><dd>{view.department}</dd></div><div><dt>Reports to</dt><dd>{user.name}</dd></div><div><dt>Joined</dt><dd>{String(view.joined_at || "—")}</dd></div></dl></div></Modal>}
    {removeRow && <Modal title="Delete account?" onClose={()=>setRemoveRow(null)}><div className="confirm-copy"><span><Trash2/></span><p><strong>{removeRow.name}</strong> will be permanently removed from this workspace.</p></div><div className="flex end"><Button className="secondary" onClick={()=>setRemoveRow(null)}>Cancel</Button><Button className="danger-btn" disabled={busy} onClick={async()=>{try{setBusy(true);await remove("employees",removeRow.id);setNotice(`${removeRow.name} deleted successfully.`);setRemoveRow(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?"Deleting…":"Yes, delete"}</Button></div></Modal>}
  </div>;
}

function PeopleForm({role,row,onClose,onSave,busy}:{role:Role;row?:Entity;onClose:()=>void;onSave:(v:FormData)=>void;busy:boolean}) { const [form,setForm]=useState<FormData>({name:row?.name||"",email:row?.email||"",phone:String(row?.phone||""),department:row?.department||departments[0],status:(row?.status as FormData["status"])||"Active"}); const [validation,setValidation]=useState(""); const field=(key:keyof FormData)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value}); return <Modal title={`${row?"Edit":"Add"} ${roleLabels[role]}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const result=schema.safeParse(form);if(!result.success){setValidation(result.error.issues[0]?.message||"Check the form.");return}onSave(result.data)}}><div className="form-grid"><label>Full name *<input value={form.name} onChange={field("name")} autoFocus/></label><label>Email address *<input type="email" value={form.email} onChange={field("email")}/></label><label>Phone number<input value={form.phone} onChange={field("phone")} placeholder="+91 98765 43210"/></label><label>Department<select value={form.department} onChange={field("department")}>{departments.map(x=><option key={x}>{x}</option>)}</select></label><label>Role<input value={roleLabels[role]} disabled/></label><label>Status<select value={form.status} onChange={field("status")}><option>Active</option><option>Inactive</option><option>On Leave</option></select></label></div>{validation&&<p className="error">{validation}</p>}<div className="flex end"><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Save account"}</Button></div></form></Modal> }
